"""add hobby to user table

Revision ID: 4ab2b147d12d
Revises: 3933c06c8ad0
Create Date: 2020-12-14 19:26:10.643184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab2b147d12d'
down_revision = '3933c06c8ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hobby', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['hobby'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'hobby')
    # ### end Alembic commands ###
