"""add profilpic to user

Revision ID: 62c895123bce
Revises: 203b69909455
Create Date: 2020-12-17 18:49:45.396837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c895123bce'
down_revision = '203b69909455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilepic', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilepic')
    # ### end Alembic commands ###
